[style.description]
underline = false
bold = false
italic = false

[style.example_text]
foreground = "white" # NOTE: this becomes black on my terminal
underline = false
bold = false
italic = false

[style.command_name]
foreground = "red"
underline = false
bold = false
italic = true

[style.example_code]
foreground = "blue"
underline = false
bold = true
italic = false

[style.example_variable]
foreground = "purple"
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = false
auto_update_interval_hours = 720

# NOTE: need to change this
[directories]
custom_pages_dir = "/home/baxterhc/.local/share/tealdeer/pages/"
