# -*- mode: ruby -*-
# vi: set ft=ruby :
# Download: https://developer.hashicorp.com/vagrant/downloads
# Configure: https://developer.hashicorp.com/vagrant/docs/vagrantfile
# Prerequisites:
#   apt install vagrant
#   vagrant plugin install vagrant-disksize vagrant-vbguest

$script = <<-'SCRIPT'
sudo apt install -y ghidra llvm-13 cmake
touch /home/vagrant/.bashrc
echo 'export LLVM_DIR=/usr/lib/llvm-13' >> .zshrc
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  # NOTE: username and password should be "vagrant"
  config.vm.synced_folder "./", "/home/vagrant/security", type: "virtualbox"
  config.disksize.size = "40GB"
  config.vm.provider "virtualbox" do |v|
    v.name = "kali"
    v.gui = true
    v.cpus = 2
    v.memory = "8192"
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
  config.vm.provision "shell", inline: $script
end
